version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
   commands:
      - sudo usermod -a -G docker ubuntu
      - sudo docker version
      - docker version
   #commands:
     # apt-get install -y docker
  pre_build:
    commands:
      # echo Just listing basic information about the environment
      - echo logging in docker images
      # which mvn
      - docker login -u shobhitdockeribm -p lastweek123
      - mvn -version
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - sudo docker build -t helloworldwebappdocker:v1 -f HelloWorldDockerfile .
      - sudo docker tag helloworldwebappdocker:v1 shobhitdockeribm/helloworldwebappdocker:v1
      #- mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Working on creating the tar ball with the WAR and AppSpec file for CodeDeploy
      - sudo docker push shobhitdockeribm/helloworldwebapp:v1
      #- mkdir appfiles
      #- cd appfiles
      #- cp ../target/HelloWorld-2.war .
      #- cp ../appspec.yml .
      #- ls -al
      #- tar -zcvf ../target/HelloWorld2.tar.gz *.*
      #- cd ..
artifacts:
  files:
# IMPORTANT
# You have to use the tar.gz if you are manually executing CodeDeploy
    #- target/HelloWorld2.tar.gz
# Use the individual files if you are using the CodeDeploy from CodePipeline
# Reason is pipeline does not untar and errors out saying that the appspec file is not there
#    - appfiles/appspec.yml
#    - appfiles/HelloWorld-1.war
  discard-paths: yes
